### ISSUE TITLE
graphql-server v3.0.0b1 does not work with aiohttp in async mode with graphiql

### ISSUE THREAD

**Issue by ketanbshah** [graphql-python/graphql-server#64]
I had to change graphqlview.py at line 155 as  follows

```python
exec_res = (
    [ex if ex is None or isinstance(ex, ExecutionResult) else await ex for ex in execution_results]
    if self.enable_async
    else execution_results
)
```

**from**

```python
exec_res = (
    [await ex for ex in execution_results]
    if self.enable_async
    else execution_results
)
```

**Comment by r-owen** [comment]
Thank you for this fix.

The problem I was observing was:
```
GraphQLView.attach(..., enable_async=True, graphiql=True)
```
caused this exception:
```
Traceback (most recent call last):
  File "/Users/rowen/UW/LSST/tsrepos/owl/.tox/run/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/rowen/UW/LSST/tsrepos/owl/.tox/run/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/Users/rowen/UW/LSST/tsrepos/owl/.tox/run/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/Users/rowen/UW/LSST/tsrepos/owl/.tox/run/lib/python3.7/site-packages/safir/middleware.py", line 141, in bind_logger
    response = await handler(request)
  File "/Users/rowen/UW/LSST/tsrepos/owl/.tox/run/lib/python3.7/site-packages/graphql_server/aiohttp/graphqlview.py", line 239, in _dispatch
    return await handler(request)
  File "/Users/rowen/UW/LSST/tsrepos/owl/.tox/run/lib/python3.7/site-packages/graphql_server/aiohttp/graphqlview.py", line 156, in __call__
    if self.enable_async
  File "/Users/rowen/UW/LSST/tsrepos/owl/.tox/run/lib/python3.7/site-packages/graphql_server/aiohttp/graphqlview.py", line 155, in <listcomp>
    [await ex for ex in execution_results]
"TypeError: object ExecutionResult can't be used in 'await' expression"
```

**Comment by KingDarBoja** [comment]
I didn't noticed these issues (weren't at my notifications list), but gonna checkout the linked PR and provide extra tests for handling this case. Thank you 🚀

**Comment by KingDarBoja** [comment]
Next release will contain this change :) Thanks for reporting and submitting a PR.
